version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    groups:
      wp-cli-packages:
        patterns:
          - "wp-cli/*"
    ignore:
      # @see <https://github.com/ampproject/amp-wp/issues/7501#issuecomment-1656231088>.
      - dependency-name: phpdocumentor/reflection

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    groups:
      wordpress-packages:
        patterns:
          - "@wordpress/*"
    ignore:
    # Need to be updated based on `@wordpress/element` react peer dependency version.
    - dependency-name: react
    - dependency-name: react-dom

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10

  # Config for composite GitHub Actions.
  - package-ecosystem: github-actions
    directory: "/.github/actions"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
