# Name of the draft release.
name-template: 'v$RESOLVED_VERSION'

# Name of the tag for the draft release.
tag-template: 'v$RESOLVED_VERSION'

# Group pull requests based on their labels.
categories:
  - title: '🚀 Features'
    labels:
      - 'Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Bug'

# Template for pull request changelog entry.
change-template: '- $TITLE (#$NUMBER)'

# Characters to escape in title of changelog entry so that they are not interpreted as Markdown format characters.
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# Template to use when there are no changelog entries.
no-changes-template: 'No changes.'

# Labels used to exclude pull requests from release draft.
exclude-labels:
  - 'skip-changelog'

# Sort changelog by `merged_at` or `title`.
sort-by: merged_at

# Sort changelog in ascending or descending order.
sort-direction: descending

# Auto-label pull requests based on configured matchers.
# Available matchers are `files` (glob), `branch` (regex), `title` (regex) and `body` (regex).
autolabeler:
  - label: 'Bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'

  - label: 'Enhancement'
    branch:
      - '/feature\/.+/'

template: |
  ## Changelog

  $CHANGES

  $CONTRIBUTORS
