name: Build plugin assets

description: Build and cache the plugin assets to speed up builds.

runs:
  using: 'composite'
  steps:
    - name: Cache assets directory
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
      id: assets-cache
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      with:
        path: ${{ github.workspace }}/assets
        key: ${{ runner.os }}-amp-wp-assets-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('assets/**') }}

    - name: Build plugin assets
      if: ${{ steps.assets-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: npm run build:js
