name: Auto-merge

on:
  pull_request:
    # Only run workflow when a PR is opened.
    types: [opened]

jobs:
  automerge-dependencies:
    name: Automerge dependencies
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for the PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
